AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the TF::FortiOS::SystemDnsserver resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tf_fortios_systemdnsserver.handlers.resource
      Runtime: python3.7
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tf_fortios_systemdnsserver.handlers.test_entrypoint
      Runtime: python3.7
      CodeUri: build/

