name: Generate Documentation

on:
  schedule:
    - cron: "25 1 9 * *"

jobs:
  build:
    #runs-on: ubuntu-latest 
    runs-on: self-hosted
    timeout-minutes: 4320

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: Install dependencies
      run: |
        pip install https://github.com/iann0036/cloudformation-cli/archive/master.zip
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate providers
      continue-on-error: true
      timeout-minutes: 4320
      run: |
        apt -y install curl unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        python util/providerscript.py > util/providers.sh
        bash util/providers.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Commit files
      run: |
        rm util/providers.sh
        rm .gitignore
        mv .docsgitignore .gitignore
        git config --local user.email "cfntfbot@ian.mn"
        git config --local user.name "iann0036[bot]"
        git add -A
        git commit -m "Documentation Update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        branch: docs
        force: true