name: Generate Documentation

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 22 1 * *"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 720

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate providers
      continue-on-error: true
      timeout-minutes: 720
      run: |
        python util/providerscript.py > util/providers.sh
        bash util/providers.sh
    - name: Commit files
      run: |
        rm util/providers.sh
        rm .gitignore
        mv .docsgitignore .gitignore
        git config --local user.email "cfntfbot@ian.mn"
        git config --local user.name "iann0036[bot]"
        git add -A
        git commit -m "Documentation Update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs
        force: true